### ISSUE TITLE
Consider recovering if workspace/workspaceFolder request gets an error reply

### ISSUE THREAD

**Issue by krobelus** [bash-lsp/bash-language-server#449]
The [kak-lsp LSP client](https://github.com/kak-lsp/kak-lsp) does not support the `workspace/workspaceFolders` request.

Since the LSP spec states: "Every processed request must send a response back to the sender of the request.", we send a `MethodNotFound` error in this case. This avoids that the language server blocks (waiting for us to reply).

Since we added that, `bash-language-server` stopped working properly. Looks like it treats this as fatal error. I think it shouldn't, since some features work without it.

Log excerpt:

```
Jul 02 16:26:37.377 DEBG To server: {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":0}, module: kak_lsp::language_server_transport:177
Jul 02 16:26:37.378 DEBG From server: {"jsonrpc":"2.0","id":1,"method":"workspace/workspaceFolders","params":null}, module: kak_lsp::language_server_transport:151
Jul 02 16:26:37.378 WARN Unsupported method: workspace/workspaceFolders, module: kak_lsp::controller:334
Jul 02 16:26:37.378 DEBG To server: {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}, module: kak_lsp::language_server_transport:177
Jul 02 16:26:37.379 DEBG From server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"onCompletion 1:1 word=null"}}, module: kak_lsp::language_server_transport:151
Jul 02 16:26:37.379 DEBG To editor `547650`: echo -debug LSP: 'onCompletion 1:1 word=null', module: kak_lsp::editor_transport:84
Jul 02 16:26:37.405 ERRO Language server error: /usr/lib/bash-language-server/node_modules/vscode-jsonrpc/lib/main.js:449
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Method not found
    at handleResponse (/usr/lib/bash-language-server/node_modules/vscode-jsonrpc/lib/main.js:449:48)
    at processMessageQueue (/usr/lib/bash-language-server/node_modules/vscode-jsonrpc/lib/main.js:276:17)
    at Immediate.<anonymous> (/usr/lib/bash-language-server/node_modules/vscode-jsonrpc/lib/main.js:260:13)
    at processImmediate (node:internal/timers:466:21) {
  code: -32601,
  data: undefined
}
, module: kak_lsp::language_server_transport:58
Jul 02 16:26:37.405 ERRO failed to fill whole buffer, module: kak_lsp::language_server_transport:74
Jul 02 16:26:37.406 DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:188
Jul 02 16:26:37.406 INFO Waiting for Messages to language server to finish..., module: kak_lsp::thread_worker:19
Jul 02 16:26:37.406 DEBG Waiting for language server process end, module: kak_lsp::language_server_transport:87
```

**Comment by skovhus** [comment]
Sorry for the late reply. How can I reproduce this error? I'm wondering what we would need to change.

**Comment by krobelus** [comment]
it is possible to reproduce by running a client that does not support workspace/workspaceFolder, like kak-lsp before 4ee7763aa04e72e9145ddd86346a5c813a1eebaa. You'd want to follow the official installation instructions but actually that's not even necessary because the fix should be easy:

if during `initialize`, the client does not send `ClientCapability.workspace.workspaceFolders = true`,
then `bash-language-server` should fall back to using `rootUri` (or `rootPath` I guess), and never ask the client for `workspace/workspaceFolders`.
It's not a big deal since it's fixed in my client and I don't know of any other client that does not implement workspaceFolders. But if you want to fix it, I'd be happy to test it.

**Comment by skovhus** [comment]
Can you still reproduce this with the latest version `bash-language-server@4.0.0-beta.6`?
